'use client';
import { useCallback, useEffect, useState } from 'react';
import { adminFetch } from '@/utils/admin-fetch';
import styles from './PetUnsubscriptionsTable.module.css';

interface PendingRequest { id:string; pet_name:string; reason:string; description:string; requested_at:string; user:{ first_name?:string; last_name?:string; email?:string }|null }

export default function PetUnsubscriptionsTable({ refreshKey=0 }:{ refreshKey?:number }) {
 const [items,setItems]=useState<PendingRequest[]>([]); const [loading,setLoading]=useState(true); const [workingId,setWorkingId]=useState<string|null>(null);
 const load=useCallback(async()=>{ setLoading(true); try { const response=await adminFetch('/api/admin/pet-unsubscriptions'); const data=await response.json(); if(!response.ok) throw new Error(data.error||'No se pudo cargar la cola.'); setItems(data.requests||[]); } catch(error){ console.error('[PetUnsubscriptionsTable]',error); } finally { setLoading(false); } },[]);
 useEffect(()=>{ void load(); },[load,refreshKey]);
 async function review(id:string,action:'approve'|'reject'){ const confirmation=action==='approve'?'¿Aprobar la baja? El espacio quedará disponible para registrar otro peludo.':'¿Rechazar la baja? El peludo continuará activo.'; if(!window.confirm(confirmation))return; const notes=window.prompt('Notas internas (opcional):')||''; setWorkingId(id); try{ const response=await adminFetch(`/api/admin/pet-unsubscriptions/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,notes})}); const data=await response.json(); if(!response.ok)throw new Error(data.error||'No se pudo procesar.'); await load(); }catch(error){window.alert(error instanceof Error?error.message:'No se pudo procesar.');}finally{setWorkingId(null);} }
 return <section className={styles.panel}><header className={styles.header}><div><span className={styles.eyebrow}>Gestión de la manada</span><h2>Solicitudes de baja de peludos</h2><p>Revisa cada solicitud antes de liberar un espacio de la membresía.</p></div><span className={styles.count}>{items.length} pendientes</span></header>{loading?<div className={styles.empty}>Cargando solicitudes…</div>:items.length===0?<div className={styles.empty}>No hay solicitudes pendientes.</div>:<div className={styles.list}>{items.map(item=>{const member=`${item.user?.first_name||''} ${item.user?.last_name||''}`.trim()||item.user?.email||'Miembro';return <article className={styles.card} key={item.id}><div className={styles.petIcon}>🐾</div><div className={styles.details}><div className={styles.titleRow}><h3>{item.pet_name}</h3><span>En revisión</span></div><p className={styles.member}>{member}</p><p><strong>Motivo:</strong> {item.reason}</p>{item.description&&<p className={styles.description}>{item.description}</p>}<small>{new Date(item.requested_at).toLocaleString('es-MX')}</small></div><div className={styles.actions}><button disabled={workingId===item.id} onClick={()=>review(item.id,'reject')} className={styles.secondary}>Rechazar</button><button disabled={workingId===item.id} onClick={()=>review(item.id,'approve')} className={styles.primary}>Aprobar baja</button></div></article>})}</div>}</section>;
}
