-- Migration: Add notification preferences to users table
ALTER TABLE users 
ADD COLUMN IF NOT EXISTS notif_email BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS notif_whatsapp BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS notif_alerts BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS notif_payments BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS notif_news BOOLEAN DEFAULT TRUE;
